<?php

namespace EL\AppBundle\Repository;

/**
 * BiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiereRepository extends \Doctrine\ORM\EntityRepository
{
}
